coverage:
  status:
    # master branch only
    project:
      default:
        # Fail the status if coverage drops by >= 0.1%
        threshold: 0.1
    patch:
      default:
        target: 80%
        # Only post a patch status to pull requests
        only_pulls: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

ignore:
  - "detekt-gradle-plugin/"
