version: 2.1

jobs:
  build:
    working_directory: ~/ddd-example

    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout
      - run:
          name: "Run gradle check task"
          command: "./gradlew clean check"
      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/libs/

workflows:
  build-workflow:
    jobs:
      - build
