name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup jdk 11 for x64
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distirbution: temurin
          architecture: x64
          cache: gradle

      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Run gradle dependences task
        run: ./gradlew clean dependences

      - name: Run gradle bootJar task
        run: ./gradlew bootJar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs

      - name: Cleanup gradle cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties

#  quality:
#  build image/upload image hub/ docker in docker or vm?
