name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup jdk 11 for x64
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
          architecture: x64
          cache: gradle

      - name: Run gradle test task
        run: ./gradlew test

      - name: Run gradle bootJar task
        run: ./gradlew bootJar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs

      - name: Cleanup gradle cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties

      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}

#  quality:
#  build image/upload image hub/ docker in docker or vm?
