name: Detekt Scanning

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  without-type-resolution:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup jdk 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          architecture: x64
          cache: gradle

      - name: Run detekt
        run: ./gradlew detekt

      - name: Upload SARIF to Github using the upload-sarif action
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt.sarif
