name: Release to docker

on:
  release:
    types:
      - published

jobs:
  workflows:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Container registry Login
        uses: docker/login-action@v1.12.0
        with:
          username: elmi
          password: ${{secrets.DOCKER_PWD}}

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}

      - name: Build & Push
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
