name: Release to docker

on:
  push:
    tags:
      - '*.*.*'

jobs:
  workflows:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Container registry Login
        uses: docker/login-action@v2
        with:
          username: elmi
          password: ${{secrets.DOCKER_PWD}}

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: elmi/ddd-example

      - name: Build & Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{github.event_name != 'pull_request'}}
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
